### ISSUE TITLE
Need firmware for better Wifi-connection!

### ISSUE THREAD

**Issue by Schpr** [Bomel/github-todoist-connector#2]
Wifi speed isn#t where it should be, if running as access pint in LAN.(https://www.tp-link.com/de/support/download/archer-c2/v3/) TP-Firmware sucks!!!1!

Schreib Scherge, schreib!

**Comment by keiwanjamaly** [comment]
Confirm, I will write new TP-Link OS

**Comment by Schpr** [comment]
> Confirm, I will write new TP-Link OS

https://media4.giphy.com/media/pCO5tKdP22RC8/200w.webp?cid=ecf05e471qmr7h87xof51b2sest0g3s8pbamoznyq2a0fe44&rid=200w.webp
